module.exports = {
  purge: [],
  theme: {
    container: {
      center: true,
    },
    extend: {
      colors: {
        "xlry-blue": "#36BEE5",
      },
      lineHeight: {
        "extra-loose": "2.5",
        "12": "3rem",
        "13": "3.25rem",
        "14": "3.5rem",
        "15": "3.75rem",
        relaxedloose: "1.8",
      },
      spacing: {
        "1-2": "0.375rem",
        "28": "7rem",
        "72": "18rem",
        "84": "21rem",
        "96": "24rem",
      },
      gridTemplateRows: {
        "12": "repeat(12, minmax(0, 1fr))",
        layout: "200px minmax(900px, 1fr) 100px",
      },
      gridRowStart: {
        "8": "8",
        "9": "9",
        "10": "10",
        "11": "11",
        "12": "12",
        "13": "13",
      },
      gridRowEnd: {
        "8": "8",
        "9": "9",
        "10": "10",
        "11": "11",
        "12": "12",
        "13": "13",
      },
    },
    fontFamily: {
      nunito: ["Nunito"],
      almarai: ["Almarai"],
      cabin: ["Cabin"],
      heebo: ["Heebo"],
      lato: ["Lato"],
      librefranklin: ["Libre Franklin"],
      mukta: ["Mukta"],
      mulish: ["Mulish"],
      poppins: ["Poppins"],
      rubik: ["Rubik"],
      varelaround: ["Varela Round"],
    },
    fontSize: {
      xs: ".75rem",
      sm: ".875rem",
      tiny: ".875rem",
      base: "1rem",
      lg: "1.125rem",
      xl: "1.25rem",
      "2xl": "1.5rem",
      "3xl": "1.875rem",
      "4xl": "2.25rem",
      "4.5xl": "2.75rem",
      "5xl": "3rem",
      "6xl": "4rem",
      "7xl": "4.5rem",
      "8xl": "6rem",
      "9xl": "7rem",
      "10xl": "8rem",
      "12xl": "10rem",
    },
  },
  variants: {},
  plugins: [],
};
