module.exports = {
  purge: [],
  theme: {
    container: {
      center: true,
    },
    extend: {
      colors: {
        "xlry-blue": "#36BEE5",
      },
      lineHeight: {
        "extra-loose": "2.5",
        "12": "3rem",
        relaxedloose: "1.8",
      },
      spacing: {
        "1-2": "0.375rem",
        "28": "7rem",
        "72": "18rem",
        "84": "21rem",
        "96": "24rem",
      },
    },
    fontFamily: {
      sans: [
        "system-ui",
        "-apple-system",
        "BlinkMacSystemFont",
        "Segoe UI",
        "Roboto",
        "Helvetica Neue",
        "Arial",
        "Noto Sans",
        "sans-serif",
        "Apple Color Emoji",
        "Segoe UI Emoji",
        "Segoe UI Symbol",
        "Noto Color Emoji",
      ],
      serif: ["Georgia", "Cambria", "Times New Roman", "Times", "serif"],
      mono: ["Menlo", "Monaco", "Consolas", "Liberation Mono", "Courier New", "monospace"],
    },
    fontSize: {
      xs: ".75rem",
      sm: ".875rem",
      tiny: ".875rem",
      base: "1rem",
      lg: "1.125rem",
      xl: "1.25rem",
      "2xl": "1.5rem",
      "3xl": "1.875rem",
      "4xl": "2.25rem",
      "5xl": "3rem",
      "6xl": "4rem",
      "7xl": "5rem",
      "8xl": "6rem",
      "9xl": "7rem",
      "10xl": "8rem",
      "12xl": "10rem",
      "45xl": "2.75rem",
    },
  },
  variants: {},
  plugins: [],
};
